# vim ft=yaml
os: linux
dist: xenial

language: python
cache: pip

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - CHECK_TYPE="tests"
    - INSTALL_DEPENDS="pip setuptools"
    - DEPENDS="-r min-requirements.txt"

before_install:
  - python -m pip install --upgrade pip virtualenv
  - virtualenv --python=python /tmp/venv
  - source /tmp/venv/bin/activate
  - python --version
  - python -m pip --version
  - python -m pip install --upgrade $INSTALL_DEPENDS
  - python -m pip --version

install:
  - if [ -n "$DEPENDS" ]; then python -m pip install $DEPENDS; fi
  - python -m pip install .
  - python -c "import sdcflows; print(sdcflows.__version__)"

before_script:
  - travis_retry python -m pip install "sdcflows[$CHECK_TYPE]"

script:
  - pytest -n 2 -v --cov sdcflows --cov-report xml:cov.xml --doctest-modules sdcflows

after_script:
  - python -m pip install codecov
  - python -m codecov --flags travis --file cov.xml -e $TRAVIS_JOB_NUMBER
